### ISSUE TITLE
honggfuzz fails to build with binutils ≥ 2.39

### ISSUE THREAD

**Issue by jtojnar** [camshaft/bolero#233]
Trying to work around #79, I tried building `cargo-bolero` with `honggfuzz` feature but that fails:

```
  linux/bfd.c: In function 'arch_bfdDisasm':
  linux/bfd.c:231:5: error: too few arguments to function 'init_disassemble_info'
    231 |     init_disassemble_info(&info, instr, arch_bfdFPrintF);
        |     ^~~~~~~~~~~~~~~~~~~~~
  In file included from linux/bfd.c:29:
  /nix/store/ydgpn6fvm1wlhxdk4x8a4hs29nzm1shg-binutils-2.41-dev/include/dis-asm.h:480:13: note: declared here
    480 | extern void init_disassemble_info (struct disassemble_info *dinfo, void *stream,
        |             ^~~~~~~~~~~~~~~~~~~~~
  make: *** [Makefile:263: linux/bfd.o] Error 1
```

Apparently, there was a [breaking change](https://trofi.github.io/posts/254-binutils-2.39.html#breaking-api-change-init_disassemble_info) in binutils 2.39, that added another argument to the function.

- cargo-bolero: 0.11.1

**Comment by jtojnar** [comment]
Looks like this is fixed in honggfuzz master: https://github.com/google/honggfuzz/commit/37e8e813c9daa94dff29654b262268481d8c53ee

**Comment by camshaft** [comment]
Sounds good. I'll pull the latest from honggfuzz.
